%General Mission Analysis Tool(GMAT) Script
%Created: 2026-06-14 10:13:39


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
DefaultSC.DateFormat = TAIModJulian;
DefaultSC.Epoch = '21545';
DefaultSC.CoordinateSystem = EarthMJ2000Eq;
DefaultSC.DisplayStateType = Cartesian;
DefaultSC.X = 7100;
DefaultSC.Y = 0;
DefaultSC.Z = 1300;
DefaultSC.VX = 0;
DefaultSC.VY = 7.35;
DefaultSC.VZ = 1;
DefaultSC.DryMass = 850;
DefaultSC.Cd = 2.2;
DefaultSC.Cr = 1.8;
DefaultSC.DragArea = 15;
DefaultSC.SRPArea = 1;
DefaultSC.SPADDragScaleFactor = 1;
DefaultSC.SPADSRPScaleFactor = 1;
DefaultSC.AtmosDensityScaleFactor = 1;
DefaultSC.ExtendedMassPropertiesModel = 'None';
DefaultSC.NAIFId = -10000001;
DefaultSC.NAIFIdReferenceFrame = -9000001;
DefaultSC.OrbitColor = Red;
DefaultSC.TargetColor = Teal;
DefaultSC.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
DefaultSC.CdSigma = 1e+70;
DefaultSC.CrSigma = 1e+70;
DefaultSC.Id = 'SatId';
DefaultSC.Attitude = CoordinateSystemFixed;
DefaultSC.SPADSRPInterpolationMethod = Bilinear;
DefaultSC.SPADSRPScaleFactorSigma = 1e+70;
DefaultSC.SPADDragInterpolationMethod = Bilinear;
DefaultSC.SPADDragScaleFactorSigma = 1e+70;
DefaultSC.AtmosDensityScaleFactorSigma = 1e+70;
DefaultSC.ModelFile = 'aura.3ds';
DefaultSC.ModelOffsetX = 0;
DefaultSC.ModelOffsetY = 0;
DefaultSC.ModelOffsetZ = 0;
DefaultSC.ModelRotationX = 0;
DefaultSC.ModelRotationY = 0;
DefaultSC.ModelRotationZ = 0;
DefaultSC.ModelScale = 1;
DefaultSC.AttitudeDisplayStateType = 'Quaternion';
DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
DefaultSC.AttitudeCoordinateSystem = EarthMJ2000Eq;
DefaultSC.EulerAngleSequence = '321';

%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel Propagator1_ForceModel;
Propagator1_ForceModel.CentralBody = Earth;
Propagator1_ForceModel.PrimaryBodies = {Earth};
Propagator1_ForceModel.Drag = None;
Propagator1_ForceModel.SRP = Off;
Propagator1_ForceModel.RelativisticCorrection = Off;
Propagator1_ForceModel.ErrorControl = RSSStep;
Propagator1_ForceModel.GravityField.Earth.Degree = 4;
Propagator1_ForceModel.GravityField.Earth.Order = 4;
Propagator1_ForceModel.GravityField.Earth.StmLimit = 100;
Propagator1_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
Propagator1_ForceModel.GravityField.Earth.TideModel = 'None';

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn ImpulsiveBurn1;
ImpulsiveBurn1.CoordinateSystem = Local;
ImpulsiveBurn1.Origin = Earth;
ImpulsiveBurn1.Axes = VNB;
ImpulsiveBurn1.Element1 = 1;
ImpulsiveBurn1.Element2 = 0;
ImpulsiveBurn1.Element3 = 0;
ImpulsiveBurn1.DecrementMass = false;
ImpulsiveBurn1.Isp = 300;
ImpulsiveBurn1.GravitationalAccel = 9.81;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create ReportFile ReportFile1;
ReportFile1.SolverIterations = Current;
ReportFile1.UpperLeft = [ 0 0 ];
ReportFile1.Size = [ 0 0 ];
ReportFile1.RelativeZOrder = 0;
ReportFile1.Maximized = false;
ReportFile1.Filename = './out.txt';
ReportFile1.Precision = 16;
ReportFile1.Add = {DefaultSC.ElapsedSecs, DefaultSC.EarthMJ2000Eq.X, DefaultSC.EarthMJ2000Eq.Y, DefaultSC.EarthMJ2000Eq.Z, DefaultSC.EarthMJ2000Eq.VX, DefaultSC.EarthMJ2000Eq.VY, DefaultSC.EarthMJ2000Eq.VZ};
ReportFile1.WriteHeaders = true;
ReportFile1.LeftJustify = On;
ReportFile1.ZeroFill = Off;
ReportFile1.FixedWidth = false;
ReportFile1.Delimiter = ',';
ReportFile1.ColumnWidth = 23;
ReportFile1.WriteReport = true;
ReportFile1.AppendToExistingFile = false;

%----------------------------------------
%---------- User Objects
%----------------------------------------

Create OpenFramesView DefaultOrbitView_View;
DefaultOrbitView_View.ViewFrame = CoordinateSystem;
DefaultOrbitView_View.ViewTrajectory = Off;
DefaultOrbitView_View.InertialFrame = Off;
DefaultOrbitView_View.SetDefaultLocation = On;
DefaultOrbitView_View.DefaultEye = [ 30000 0 0 ];
DefaultOrbitView_View.DefaultCenter = [ 0 0 0 ];
DefaultOrbitView_View.DefaultUp = [ 0 0 1 ];
DefaultOrbitView_View.SetCurrentLocation = Off;
DefaultOrbitView_View.FOVy = 45;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(DefaultSC) {DefaultSC.ElapsedSecs = 12000.0};
Maneuver ImpulsiveBurn1(DefaultSC);
Propagate DefaultProp(DefaultSC) {DefaultSC.ElapsedSecs = 12000.0};
